### ISSUE TITLE
Daily repeated post

### ISSUE THREAD

**Issue by HKGIOS** [siutsin/telegram-jung2-bot#2597] opened 2024-01-05 13:49 UTC
Please fix the bot posted two or three times when 6pm HK time, thank you

**Comment by siutsin** [comment] 2024-01-06 03:44
Will have a look over the weekend

**Comment by HKGIOS** [comment] 2024-01-08 10:57
today posted 6 times
e.g.
18:00 18:05 18:10 18:20 18:25 18:30

**Comment by siutsin** [comment] 2024-01-08 13:09
The issue is challenging to reproduce due to its occurrence only during the default daily offWork schedule, and that is introduced from the recent infrastructure migration. Several trials and errors may be necessary, and this situation could persist for the next couple of days (Hopefully). As a workaround, use `/setOffFromWorkTimeUTC` to adjust the offWork time, for example to 5:45 pm, to avoid peak hours.

**Comment by siutsin** [comment] 2024-01-12 13:45
This has been fixed in https://github.com/siutsin/otaru/pull/197, and the offWork schedule has been stable for the past few days, although delays vary between groups. However, this is a separate issue. Closing now.

**Closed by siutsin** 2024-01-12 13:45 UTC
